// Generated by CoffeeScript 1.6.1
(function() {
  var app, db, express, http, path, redis, routes, server;

  express = require("express");

  routes = require("./routes");

  http = require("http");

  path = require("path");

  app = express();

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.favicon(__dirname + '/public/images/pong.ico', {
      maxAge: 2592000000
    }));
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(require("stylus").middleware(__dirname + "/public"));
    return app.use(express["static"](path.join(__dirname, "public")));
  });

  app.configure("development", function() {
    return app.use(express.errorHandler());
  });

  redis = require("redis");

  db = redis.createClient();

  app.get("/", routes.index);

  app.get("/download", routes.download);

  app.get("/register", routes.register);

  app.get("/donate", routes.donate);

  app.get("/thanks", routes.donate);

  app.get("/about", routes.about);

  app.post("/register", routes.register_post(db));

  app.get("/hiscore/:id", routes.hiscore(db));

  app.post("/hiscore", routes.hiscore_post(db));

  server = http.createServer(app);

  server.listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
